name: Selenium Functional Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.0

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Instalar Chrome y ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y wget unzip xvfb
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        wget -O chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip" || true
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Ejecutar prueba funcional
      run: |
        python selenium_test_funcional/test_busqueda.py
